# Generated by Django 4.0 on 2025-02-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='MovieTagName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='YearMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('uptime_at', models.DateTimeField(verbose_name='投稿時間')),
                ('movie_file', models.ImageField(default='', max_length=200, upload_to='media', verbose_name='動画ファイル')),
                ('description', models.TextField(max_length=300, verbose_name='概要')),
                ('category', models.ForeignKey(choices=[('dailylife', '日常'), ('music', '音楽'), ('game', 'ゲーム')], max_length=50, on_delete=django.db.models.deletion.PROTECT, to='youtubeapp.category', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='MovieTagList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubeapp.yearmovie')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubeapp.movietagname')),
            ],
        ),
    ]
